---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sugardonblog
spec:
  project: default
  source:
    directory:
      recurse: false
    path: applications/sugardonblog
    repoURL: https://github.com/sugardon-org/manifests
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: sugardonblog
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
