---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: e590a095d063468d3b4e70dd5b9e71bbfcf9db91
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
