---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 80c5db2bf8d40ea34fde3e0c87d48ac81610c5d3
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
