---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 6e980818f1693b8ac60c6c911f51d17b033ca20b
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
