---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 3f29bed8cee85dd103f1772ca174df840c0b2633
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
