---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 3c09065d00e4a3e1301f3865f5c0631024a49752
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
