---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: d6f98f0a5904e44b3fc9dbd5f87d5ae4cd329549
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
