---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 1bfc872245bf529833cdda2f0b3711bd3f10c72e
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
