---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: f7abf792567e55f8d1b8ba8aa58997eb6eb977d3
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
