---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 92fa55cb90b710fb74ebde1f9d606e487f46ca42
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
