---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 96e5a92b90f4f4168d7103a729dfa1dd7c28a52a
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
