---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: cc7275752026bc2128f9502d51240734362f6aaa
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
