---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 2af8748e84d19a204cc0b22ec65db581541a7be4
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
