---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 73f1e1232cb45d5e165a2e404b0f5c2d8cf5f387
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
