---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: d17f34a2f8798672aab947d2222718ce9b2d6bcd
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
