---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: c0992a24f024b6b376e63dfa5106e56183f8b7d4
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
