---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: e59aa008af22224fa0b3d48eb9cee8186764a428
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
