---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 34f042cccc7c2c8d5c8018c919a1247617f54dbe
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
