---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 06fb501742b22aabc274eb343d21d9a03e1d5223
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
