---
nextjs:
  image:
    repository: sugardon/sugardonblog
    tag: 10bf08d4846657ddd9ccf54b8622725568438437
  certificate:
    enabled: true
    domain: "blog.sugardon.com"
    secretName: sugardonblog-tls
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
  emissaryIngress:
    enabled: true
    domain: "blog.sugardon.com"
    tlsSecretName: sugardonblog-tls
