---
name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          sudo apt-get install yamllint
      - name: run
        run: |
          make yamllint

  kustomizebuild:
    name: kustomizebuild
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: k8s.gcr.io/kustomize/kustomize:v4.5.5
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          make kustomizebuild
